import 'server-only';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { drawLetterhead } from '@/lib/pdf/letterhead';
import { EMBLEM_PNG_BASE64 } from '@/lib/pdf/brand-marks';

const NAVY = rgb(0.106, 0.165, 0.290);
const GOLD = rgb(0.627, 0.49, 0.204);
const CHARCOAL = rgb(0.063, 0.059, 0.051);
const MUTE = rgb(0.45, 0.42, 0.38);
const LINE = rgb(0.85, 0.83, 0.79);
const WHITE = rgb(1, 1, 1);
const ascii = (s: string) => (s || '').replace(/₹/g, 'Rs.').replace(/[^\x20-\x7E]/g, ' ');

export interface StmtColumn { label: string; align?: 'left' | 'right'; weight?: number }
export interface StmtRow { cells: string[]; kind?: 'normal' | 'head' | 'total' }
export interface TallyStatementData {
  company: { name: string; registeredAddress?: string; phone?: string; email?: string; website?: string; gstin?: string };
  title: string;
  subtitle?: string;
  columns: StmtColumn[];
  rows: StmtRow[];
}

/** A branded, navy + gold financial statement page for Ameya Tally reports. */
export async function buildTallyStatementPdf(d: TallyStatementData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  let page = doc.addPage([595.28, 841.89]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const emblem = await doc.embedPng(Buffer.from(EMBLEM_PNG_BASE64, 'base64'));
  const W = 595.28, M = 48;
  const usable = W - 2 * M;

  const totalWeight = d.columns.reduce((s, c) => s + (c.weight ?? 1), 0);
  const xs: number[] = [];
  let acc = M;
  for (const c of d.columns) { xs.push(acc); acc += (usable * (c.weight ?? 1)) / totalWeight; }
  const colRight = (i: number) => (i + 1 < d.columns.length ? xs[i + 1]! : W - M) - 6;

  const draw = (s: string, x: number, y: number, size: number, f = font, c = CHARCOAL) => page.drawText(ascii(s), { x, y, size, font: f, color: c });
  const drawR = (s: string, xr: number, y: number, size: number, f = font, c = CHARCOAL) => page.drawText(ascii(s), { x: xr - f.widthOfTextAtSize(ascii(s), size), y, size, font: f, color: c });

  const { headerBottom } = drawLetterhead(page, { font, bold }, {
    legalName: d.company.name, registeredAddress: d.company.registeredAddress,
    phone: d.company.phone, email: d.company.email, website: d.company.website, gstin: d.company.gstin,
  }, { emblem });

  let y = headerBottom - 24;
  draw(d.title, M, y, 14, bold, NAVY);
  if (d.subtitle) drawR(d.subtitle, W - M, y, 9, font, MUTE);
  y -= 22;

  const headerRow = () => {
    page.drawRectangle({ x: M, y: y - 5, width: usable, height: 18, color: NAVY });
    d.columns.forEach((c, i) => {
      if (c.align === 'right') drawR(c.label, colRight(i), y, 8.5, bold, WHITE);
      else draw(c.label, xs[i]! + 4, y, 8.5, bold, WHITE);
    });
    y -= 22;
  };
  headerRow();

  for (const r of d.rows) {
    if (y < 120) { // new page
      page = doc.addPage([595.28, 841.89]);
      drawLetterhead(page, { font, bold }, { legalName: d.company.name, registeredAddress: d.company.registeredAddress, phone: d.company.phone, email: d.company.email, website: d.company.website, gstin: d.company.gstin }, { emblem });
      y = 760; headerRow();
    }
    const f = r.kind === 'normal' ? font : bold;
    const color = r.kind === 'head' ? GOLD : r.kind === 'total' ? NAVY : CHARCOAL;
    if (r.kind === 'total') page.drawLine({ start: { x: M, y: y + 12 }, end: { x: W - M, y: y + 12 }, thickness: 0.6, color: NAVY });
    r.cells.forEach((cell, i) => {
      const c = d.columns[i];
      if (c?.align === 'right') drawR(cell, colRight(i), y, 9.5, f, color);
      else draw(cell, xs[i]! + 4, y, 9.5, f, color);
    });
    if (r.kind !== 'head') page.drawLine({ start: { x: M, y: y - 5 }, end: { x: W - M, y: y - 5 }, thickness: 0.3, color: LINE });
    y -= r.kind === 'head' ? 16 : 18;
  }

  const foot = 'Generated by Ameya Tally. A management report from the CRM books — not a substitute for audited statements.';
  draw(foot, M, 100, 7, font, MUTE);
  return doc.save();
}
