'use server';
import { revalidatePath } from 'next/cache';
import { prisma } from '@/lib/db/prisma';
import { runDemandCycle, dispatchPendingDemands, type DemandRun } from '@/server/services/demand-service';
import { writeAudit } from '@/lib/audit/log';
import { ensure, toActionError } from './_helpers';

/** Generate + dispatch demands on demand (same pass the daily cron runs). */
export async function runDemands(): Promise<{ ok: true; result: DemandRun } | { error: string }> {
  try {
    await ensure('booking.manage');
    const result = await runDemandCycle();
    revalidatePath('/demands');
    return { ok: true, result };
  } catch (err) { return toActionError(err); }
}

/** Re-send the still-pending demands without generating new ones. */
export async function resendPendingDemands(): Promise<{ ok: true; dispatched: number } | { error: string }> {
  try {
    await ensure('booking.manage');
    const r = await dispatchPendingDemands(100);
    revalidatePath('/demands');
    return { ok: true, dispatched: r.dispatched };
  } catch (err) { return toActionError(err); }
}

/** Set a buyer's preferred demand/WhatsApp language (module #6): en | hi | kn | ta. */
export async function setBuyerLanguage(leadId: string, lang: string): Promise<{ ok: true } | { error: string }> {
  try {
    await ensure('booking.manage');
    const value = ['en', 'hi', 'kn', 'ta'].includes(lang) ? lang : 'en';
    await prisma.lead.update({ where: { id: leadId }, data: { preferredLang: value } });
    revalidatePath('/demands');
    return { ok: true };
  } catch (err) { return toActionError(err); }
}

export async function cancelDemand(id: string): Promise<{ ok: true } | { error: string }> {
  try {
    await ensure('booking.manage');
    await prisma.demandNotice.update({ where: { id }, data: { status: 'CANCELLED' } });
    await writeAudit({ action: 'UPDATE', entityType: 'DemandNotice', entityId: id, summary: 'Demand cancelled' });
    revalidatePath('/demands');
    return { ok: true };
  } catch (err) { return toActionError(err); }
}

/**
 * Raise a demand by hand.
 *
 * Everything on this screen was generated by the nightly cycle from a payment
 * milestone, which is right for a schedule that is being followed and useless the
 * moment it is not: a one-off ask — a maintenance deposit, a corpus contribution,
 * an agreed part-payment settled over the phone — had nowhere to go and got sent
 * from somebody's own WhatsApp, unrecorded and unchased.
 *
 * A demand still only *asks*. Collection lands where it always did, on the
 * milestone and the voucher; nothing here moves money.
 */
export async function createDemand(input: {
  bookingId: string; label: string; amount: number; dueDate?: string | null; milestoneId?: string | null;
}): Promise<{ ok: true; id: string; number: string } | { error: string }> {
  try {
    const ctx = await ensure('booking.manage');
    const label = (input.label ?? '').trim();
    const amount = Number(input.amount);
    if (!input.bookingId) return { error: 'Pick the booking this is against.' };
    if (label.length < 2) return { error: 'Say what the demand is for.' };
    if (!Number.isFinite(amount) || amount <= 0) return { error: 'Enter an amount above zero.' };

    const booking = await prisma.booking.findUnique({
      where: { id: input.bookingId },
      select: { id: true, reference: true, lead: { select: { name: true } } },
    });
    if (!booking) return { error: 'That booking no longer exists.' };

    const due = input.dueDate ? new Date(input.dueDate) : null;
    if (due && Number.isNaN(due.getTime())) return { error: 'That due date does not look right.' };

    // A manual demand deliberately carries no milestone by default. Attaching one
    // would collide with the nightly generator's `@@unique([milestoneId, kind])`
    // and silently swallow the demand.
    const { docNumber, nextSequence } = await import('@/lib/db/sequence');
    const number = docNumber('DL', await nextSequence('demand:DL', prisma, 1000));

    const row = await prisma.demandNotice.create({
      data: {
        number, bookingId: booking.id, milestoneId: input.milestoneId || null,
        kind: due && due < new Date() ? 'OVERDUE' : 'UPCOMING',
        amount, dueDate: due, label, status: 'PENDING',
      },
      select: { id: true },
    });

    await writeAudit({
      actorId: ctx.user.id, action: 'CREATE', entityType: 'DemandNotice', entityId: row.id,
      summary: `Demand ${number} raised on ${booking.lead?.name ?? booking.reference} — Rs ${amount.toLocaleString('en-IN')} for ${label}`,
    });
    revalidatePath('/demands');
    return { ok: true, id: row.id, number };
  } catch (err) { return toActionError(err); }
}
