// AUTO-GENERATED connector directory for the App Exchange (v15.25).
// Client-safe: no server-only imports. Regenerate with scripts/gen-connectors (kept in repo history).
//
// "tier" is honest about reality:
//   live      = works end-to-end today (native, webhook or REST-backed)
//   available = listed and installable; wiring is provisioned by the framework
//   beta      = partially wired, being finished
// The directory is curated and grows over time; the framework supports any number.

export type ConnectorAuth = 'oauth2' | 'apikey' | 'webhook' | 'native' | 'none';
export type ConnectorTier = 'live' | 'beta' | 'available';

export interface ConnectorDef {
  slug: string;
  name: string;
  category: string;
  blurb: string;
  auth: ConnectorAuth;
  tier: ConnectorTier;
  popular?: boolean;
}

export const CONNECTOR_CATEGORIES: string[] = ["Communication", "Productivity", "Payments & Finance", "Marketing", "CRM & Sales", "Analytics & BI", "Storage & Documents", "HR & Operations", "Real Estate Portals", "Telephony & IVR", "Support & Ticketing", "Developer & Automation", "Maps & Location"];

export const CONNECTORS: ConnectorDef[] = [
  { slug:"slack", name:"Slack", category:"Communication", blurb:"Connect your Slack account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"microsoft-teams", name:"Microsoft Teams", category:"Communication", blurb:"Connect your Microsoft Teams account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"discord", name:"Discord", category:"Communication", blurb:"Send communication events to Discord in real time \u2014 no code, just a URL.", auth:"webhook", tier:"available" },
  { slug:"telegram", name:"Telegram", category:"Communication", blurb:"Paste your Telegram API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"whatsapp-business", name:"WhatsApp Business", category:"Communication", blurb:"Built-in WhatsApp Business support, tuned for how Ameya works.", auth:"native", tier:"live", popular:true },
  { slug:"twilio", name:"Twilio", category:"Communication", blurb:"Paste your Twilio API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"gmail", name:"Gmail", category:"Communication", blurb:"Connect your Gmail account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"outlook", name:"Outlook", category:"Communication", blurb:"Connect your Outlook account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"zoom", name:"Zoom", category:"Communication", blurb:"Connect your Zoom account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"google-meet", name:"Google Meet", category:"Communication", blurb:"Connect your Google Meet account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"intercom", name:"Intercom", category:"Communication", blurb:"Paste your Intercom API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"front", name:"Front", category:"Communication", blurb:"Paste your Front API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"messagebird", name:"MessageBird", category:"Communication", blurb:"Paste your MessageBird API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"vonage", name:"Vonage", category:"Communication", blurb:"Paste your Vonage API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"plivo", name:"Plivo", category:"Communication", blurb:"Paste your Plivo API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"gupshup", name:"Gupshup", category:"Communication", blurb:"Paste your Gupshup API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"interakt", name:"Interakt", category:"Communication", blurb:"Paste your Interakt API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"aisensy", name:"AiSensy", category:"Communication", blurb:"Paste your AiSensy API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"google-sheets", name:"Google Sheets", category:"Productivity", blurb:"Connect your Google Sheets account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"google-docs", name:"Google Docs", category:"Productivity", blurb:"Connect your Google Docs account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"google-calendar", name:"Google Calendar", category:"Productivity", blurb:"Connect your Google Calendar account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"microsoft-excel", name:"Microsoft Excel", category:"Productivity", blurb:"Connect your Microsoft Excel account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"notion", name:"Notion", category:"Productivity", blurb:"Connect your Notion account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"airtable", name:"Airtable", category:"Productivity", blurb:"Paste your Airtable API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"trello", name:"Trello", category:"Productivity", blurb:"Connect your Trello account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"asana", name:"Asana", category:"Productivity", blurb:"Connect your Asana account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"monday-com", name:"Monday.com", category:"Productivity", blurb:"Connect your Monday.com account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"clickup", name:"ClickUp", category:"Productivity", blurb:"Connect your ClickUp account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"todoist", name:"Todoist", category:"Productivity", blurb:"Connect your Todoist account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"coda", name:"Coda", category:"Productivity", blurb:"Paste your Coda API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"confluence", name:"Confluence", category:"Productivity", blurb:"Connect your Confluence account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"jira", name:"Jira", category:"Productivity", blurb:"Connect your Jira account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"basecamp", name:"Basecamp", category:"Productivity", blurb:"Connect your Basecamp account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"evernote", name:"Evernote", category:"Productivity", blurb:"Connect your Evernote account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"razorpay", name:"Razorpay", category:"Payments & Finance", blurb:"Paste your Razorpay API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"stripe", name:"Stripe", category:"Payments & Finance", blurb:"Paste your Stripe API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"payu", name:"PayU", category:"Payments & Finance", blurb:"Paste your PayU API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"cashfree", name:"Cashfree", category:"Payments & Finance", blurb:"Paste your Cashfree API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"paytm", name:"Paytm", category:"Payments & Finance", blurb:"Paste your Paytm API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"phonepe", name:"PhonePe", category:"Payments & Finance", blurb:"Paste your PhonePe API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"ccavenue", name:"CCAvenue", category:"Payments & Finance", blurb:"Paste your CCAvenue API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"instamojo", name:"Instamojo", category:"Payments & Finance", blurb:"Paste your Instamojo API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"zoho-books", name:"Zoho Books", category:"Payments & Finance", blurb:"Connect your Zoho Books account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"quickbooks", name:"QuickBooks", category:"Payments & Finance", blurb:"Connect your QuickBooks account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"xero", name:"Xero", category:"Payments & Finance", blurb:"Connect your Xero account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"tally-prime", name:"Tally Prime", category:"Payments & Finance", blurb:"Built-in Tally Prime support, tuned for how Ameya works.", auth:"native", tier:"live", popular:true },
  { slug:"busy-accounting", name:"Busy Accounting", category:"Payments & Finance", blurb:"Built-in Busy Accounting support, tuned for how Ameya works.", auth:"native", tier:"available" },
  { slug:"cleartax", name:"ClearTax", category:"Payments & Finance", blurb:"Paste your ClearTax API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"chargebee", name:"Chargebee", category:"Payments & Finance", blurb:"Paste your Chargebee API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"freshbooks", name:"FreshBooks", category:"Payments & Finance", blurb:"Connect your FreshBooks account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"razorpayx", name:"RazorpayX", category:"Payments & Finance", blurb:"Paste your RazorpayX API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"recko", name:"Recko", category:"Payments & Finance", blurb:"Paste your Recko API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"mailchimp", name:"Mailchimp", category:"Marketing", blurb:"Connect your Mailchimp account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"hubspot", name:"HubSpot", category:"Marketing", blurb:"Connect your HubSpot account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"marketo", name:"Marketo", category:"Marketing", blurb:"Connect your Marketo account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"meta-ads", name:"Meta Ads", category:"Marketing", blurb:"Connect your Meta Ads account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"google-ads", name:"Google Ads", category:"Marketing", blurb:"Connect your Google Ads account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"linkedin-ads", name:"LinkedIn Ads", category:"Marketing", blurb:"Connect your LinkedIn Ads account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"brevo", name:"Brevo", category:"Marketing", blurb:"Paste your Brevo API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"klaviyo", name:"Klaviyo", category:"Marketing", blurb:"Paste your Klaviyo API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"activecampaign", name:"ActiveCampaign", category:"Marketing", blurb:"Paste your ActiveCampaign API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"webengage", name:"WebEngage", category:"Marketing", blurb:"Paste your WebEngage API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"moengage", name:"MoEngage", category:"Marketing", blurb:"Paste your MoEngage API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"clevertap", name:"CleverTap", category:"Marketing", blurb:"Paste your CleverTap API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"customer-io", name:"Customer.io", category:"Marketing", blurb:"Paste your Customer.io API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"sendgrid", name:"SendGrid", category:"Marketing", blurb:"Paste your SendGrid API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"mailerlite", name:"MailerLite", category:"Marketing", blurb:"Paste your MailerLite API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"meta-lead-ads", name:"Meta Lead Ads", category:"Marketing", blurb:"Connect your Meta Lead Ads account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"salesforce", name:"Salesforce", category:"CRM & Sales", blurb:"Connect your Salesforce account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"zoho-crm", name:"Zoho CRM", category:"CRM & Sales", blurb:"Connect your Zoho CRM account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"hubspot-crm", name:"HubSpot CRM", category:"CRM & Sales", blurb:"Connect your HubSpot CRM account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"pipedrive", name:"Pipedrive", category:"CRM & Sales", blurb:"Paste your Pipedrive API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"freshsales", name:"Freshsales", category:"CRM & Sales", blurb:"Paste your Freshsales API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"leadsquared", name:"LeadSquared", category:"CRM & Sales", blurb:"Paste your LeadSquared API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"kylas", name:"Kylas", category:"CRM & Sales", blurb:"Paste your Kylas API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"close", name:"Close", category:"CRM & Sales", blurb:"Paste your Close API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"copper", name:"Copper", category:"CRM & Sales", blurb:"Paste your Copper API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"sell-do", name:"Sell.Do", category:"CRM & Sales", blurb:"Paste your Sell.Do API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"google-analytics", name:"Google Analytics", category:"Analytics & BI", blurb:"Connect your Google Analytics account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"mixpanel", name:"Mixpanel", category:"Analytics & BI", blurb:"Paste your Mixpanel API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"amplitude", name:"Amplitude", category:"Analytics & BI", blurb:"Paste your Amplitude API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"segment", name:"Segment", category:"Analytics & BI", blurb:"Paste your Segment API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"hotjar", name:"Hotjar", category:"Analytics & BI", blurb:"Paste your Hotjar API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"power-bi", name:"Power BI", category:"Analytics & BI", blurb:"Connect your Power BI account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"tableau", name:"Tableau", category:"Analytics & BI", blurb:"Paste your Tableau API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"looker-studio", name:"Looker Studio", category:"Analytics & BI", blurb:"Connect your Looker Studio account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"metabase", name:"Metabase", category:"Analytics & BI", blurb:"Paste your Metabase API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"posthog", name:"PostHog", category:"Analytics & BI", blurb:"Paste your PostHog API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"google-drive", name:"Google Drive", category:"Storage & Documents", blurb:"Connect your Google Drive account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"live", popular:true },
  { slug:"dropbox", name:"Dropbox", category:"Storage & Documents", blurb:"Connect your Dropbox account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"box", name:"Box", category:"Storage & Documents", blurb:"Connect your Box account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"onedrive", name:"OneDrive", category:"Storage & Documents", blurb:"Connect your OneDrive account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"aws-s3", name:"AWS S3", category:"Storage & Documents", blurb:"Paste your AWS S3 API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"digilocker", name:"DigiLocker", category:"Storage & Documents", blurb:"Connect your DigiLocker account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"docusign", name:"DocuSign", category:"Storage & Documents", blurb:"Connect your DocuSign account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"adobe-sign", name:"Adobe Sign", category:"Storage & Documents", blurb:"Connect your Adobe Sign account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"zoho-sign", name:"Zoho Sign", category:"Storage & Documents", blurb:"Connect your Zoho Sign account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"signeasy", name:"SignEasy", category:"Storage & Documents", blurb:"Paste your SignEasy API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"leegality", name:"Leegality", category:"Storage & Documents", blurb:"Paste your Leegality API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"digio", name:"Digio", category:"Storage & Documents", blurb:"Paste your Digio API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"darwinbox", name:"Darwinbox", category:"HR & Operations", blurb:"Paste your Darwinbox API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"keka", name:"Keka", category:"HR & Operations", blurb:"Paste your Keka API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"greythr", name:"GreytHR", category:"HR & Operations", blurb:"Paste your GreytHR API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"zoho-people", name:"Zoho People", category:"HR & Operations", blurb:"Connect your Zoho People account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"razorpayx-payroll", name:"RazorpayX Payroll", category:"HR & Operations", blurb:"Paste your RazorpayX Payroll API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"bamboohr", name:"BambooHR", category:"HR & Operations", blurb:"Paste your BambooHR API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"deel", name:"Deel", category:"HR & Operations", blurb:"Paste your Deel API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"workday", name:"Workday", category:"HR & Operations", blurb:"Connect your Workday account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"magicbricks", name:"MagicBricks", category:"Real Estate Portals", blurb:"Paste your MagicBricks API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"99acres", name:"99acres", category:"Real Estate Portals", blurb:"Paste your 99acres API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"housing-com", name:"Housing.com", category:"Real Estate Portals", blurb:"Paste your Housing.com API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"nobroker", name:"NoBroker", category:"Real Estate Portals", blurb:"Paste your NoBroker API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"proptiger", name:"PropTiger", category:"Real Estate Portals", blurb:"Paste your PropTiger API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"commonfloor", name:"CommonFloor", category:"Real Estate Portals", blurb:"Paste your CommonFloor API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"square-yards", name:"Square Yards", category:"Real Estate Portals", blurb:"Paste your Square Yards API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"rera-portal", name:"RERA Portal", category:"Real Estate Portals", blurb:"Built-in RERA Portal support, tuned for how Ameya works.", auth:"native", tier:"available", popular:true },
  { slug:"nestaway", name:"Nestaway", category:"Real Estate Portals", blurb:"Paste your Nestaway API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"sulekha", name:"Sulekha", category:"Real Estate Portals", blurb:"Paste your Sulekha API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"exotel", name:"Exotel", category:"Telephony & IVR", blurb:"Paste your Exotel API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"knowlarity", name:"Knowlarity", category:"Telephony & IVR", blurb:"Paste your Knowlarity API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"ozonetel", name:"Ozonetel", category:"Telephony & IVR", blurb:"Paste your Ozonetel API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"myoperator", name:"MyOperator", category:"Telephony & IVR", blurb:"Paste your MyOperator API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"servetel", name:"Servetel", category:"Telephony & IVR", blurb:"Paste your Servetel API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"kaleyra", name:"Kaleyra", category:"Telephony & IVR", blurb:"Paste your Kaleyra API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"meritto", name:"Meritto", category:"Telephony & IVR", blurb:"Paste your Meritto API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"callhippo", name:"CallHippo", category:"Telephony & IVR", blurb:"Paste your CallHippo API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"zendesk", name:"Zendesk", category:"Support & Ticketing", blurb:"Connect your Zendesk account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available", popular:true },
  { slug:"freshdesk", name:"Freshdesk", category:"Support & Ticketing", blurb:"Paste your Freshdesk API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"zoho-desk", name:"Zoho Desk", category:"Support & Ticketing", blurb:"Connect your Zoho Desk account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"help-scout", name:"Help Scout", category:"Support & Ticketing", blurb:"Paste your Help Scout API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"kapture-cx", name:"Kapture CX", category:"Support & Ticketing", blurb:"Paste your Kapture CX API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"happyfox", name:"HappyFox", category:"Support & Ticketing", blurb:"Paste your HappyFox API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"zapier", name:"Zapier", category:"Developer & Automation", blurb:"Send developer events to Zapier in real time \u2014 no code, just a URL.", auth:"webhook", tier:"live", popular:true },
  { slug:"make", name:"Make", category:"Developer & Automation", blurb:"Send developer events to Make in real time \u2014 no code, just a URL.", auth:"webhook", tier:"live", popular:true },
  { slug:"n8n", name:"n8n", category:"Developer & Automation", blurb:"Send developer events to n8n in real time \u2014 no code, just a URL.", auth:"webhook", tier:"live" },
  { slug:"pabbly-connect", name:"Pabbly Connect", category:"Developer & Automation", blurb:"Send developer events to Pabbly Connect in real time \u2014 no code, just a URL.", auth:"webhook", tier:"available" },
  { slug:"rest-api", name:"REST API", category:"Developer & Automation", blurb:"Paste your REST API API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"incoming-webhooks", name:"Incoming Webhooks", category:"Developer & Automation", blurb:"Send developer events to Incoming Webhooks in real time \u2014 no code, just a URL.", auth:"webhook", tier:"live", popular:true },
  { slug:"github", name:"GitHub", category:"Developer & Automation", blurb:"Connect your GitHub account securely with one click (OAuth) to sync data both ways.", auth:"oauth2", tier:"available" },
  { slug:"google-apps-script", name:"Google Apps Script", category:"Developer & Automation", blurb:"Built-in Google Apps Script support, tuned for how Ameya works.", auth:"native", tier:"live" },
  { slug:"aws-lambda", name:"AWS Lambda", category:"Developer & Automation", blurb:"Paste your AWS Lambda API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"ifttt", name:"IFTTT", category:"Developer & Automation", blurb:"Send developer events to IFTTT in real time \u2014 no code, just a URL.", auth:"webhook", tier:"available" },
  { slug:"google-maps", name:"Google Maps", category:"Maps & Location", blurb:"Paste your Google Maps API key to push and pull data on a schedule.", auth:"apikey", tier:"live", popular:true },
  { slug:"mapbox", name:"Mapbox", category:"Maps & Location", blurb:"Paste your Mapbox API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
  { slug:"mapmyindia", name:"MapmyIndia", category:"Maps & Location", blurb:"Paste your MapmyIndia API key to push and pull data on a schedule.", auth:"apikey", tier:"available", popular:true },
  { slug:"here-maps", name:"HERE Maps", category:"Maps & Location", blurb:"Paste your HERE Maps API key to push and pull data on a schedule.", auth:"apikey", tier:"available" },
];

const BY_SLUG = new Map(CONNECTORS.map((c) => [c.slug, c]));
export function connectorBySlug(slug: string): ConnectorDef | undefined { return BY_SLUG.get(slug); }
export const CONNECTOR_COUNT = CONNECTORS.length;
export const LIVE_CONNECTOR_COUNT = CONNECTORS.filter((c) => c.tier === 'live').length;

export const AUTH_LABEL: Record<ConnectorAuth, string> = {
  oauth2: 'One-click (OAuth)', apikey: 'API key', webhook: 'Webhook', native: 'Built-in', none: 'Manual',
};
