/**
 * Plain words people actually type, mapped to the screen they mean. The command
 * palette matches a query against a screen's label, its blurb *and* these
 * aliases, so someone who types "invoice", "emi", "khata" or "who owns the land"
 * still lands on the right page — even though none of those words is the menu
 * label. Keep aliases lowercase.
 */
export const SEARCH_ALIASES: Record<string, string[]> = {
  '/sales': ['enquiry', 'enquiries', 'prospect', 'prospects', 'pipeline', 'crm', 'follow up', 'followup'],
  '/walk-ins': ['walkin', 'walk in', 'visitor', 'came to site'],
  '/nri': ['overseas', 'foreign buyer', 'abroad', 'non resident'],
  '/partners': ['broker', 'brokers', 'agent', 'agents', 'channel'],
  '/inventory': ['flats', 'units', 'stock', 'availability', 'available flats', 'plots'],
  '/pricing': ['price list', 'rate', 'rates', 'commission', 'brokerage'],
  '/customers': ['buyer', 'buyers', 'owner portal', 'client', 'clients'],
  '/variations': ['change request', 'change order', 'buyer change'],
  '/billing': ['invoice', 'invoices', 'bill', 'bills', 'purchase order', 'po', 'gst invoice'],
  '/payment-requests': ['approve payment', 'payment approval', 'request money'],
  '/receivables': ['money owed', 'outstanding', 'dues', 'collections', 'emi', 'demand'],
  '/payments': ['paid', 'payment made', 'utr', 'disbursement', 'expense paid'],
  '/cash-book': ['cash', 'petty cash', 'cash in hand', 'rokad'],
  '/ledger': ['accounts', 'accounting', 'khata', 'books', 'journal'],
  '/budgets': ['budget', 'plan vs actual', 'cost plan'],
  '/treasury': ['bank', 'bank balance', 'reconcile', 'reconciliation', 'cash flow'],
  '/capital': ['escrow', 'rera account', 'investor', 'investors', 'covenant'],
  '/expenses': ['reimbursement', 'expense claim', 'claim'],
  '/procurement': ['grn', 'goods receipt', 'three way match', 'material received', 'delivery'],
  '/material-requests': ['indent', 'material request', 'ask for material'],
  '/programme': ['schedule', 'construction schedule', 'gantt', 'progress', 'boq', 'earned value'],
  '/quality': ['inspection', 'ncr', 'non conformance', 'safety', 'permit', 'hold point'],
  '/architecture': ['drawing', 'drawings', 'rfi', 'design'],
  '/transmittals': ['drawing issued', 'transmittal', 'issued drawings'],
  '/land': ['title', 'title chain', 'sanction', 'approval', 'parcel', 'who owns', 'litigation'],
  '/statutory': ['compliance', 'due date', 'filing', 'renewal', 'tax calendar'],
  '/governance': ['risk', 'risk register', 'contract', 'insurance'],
  '/lease': ['tenant', 'rent', 'rental', 'lease'],
  '/leasing': ['commercial rent', 'rent roll', 'shop rent'],
  '/association': ['cam', 'maintenance charge', 'society', 'handover'],
  '/documents': ['file', 'files', 'papers', 'upload', 'attachment'],
  '/ask': ['ask a question', 'search documents', 'find in files'],
  '/templates': ['letter', 'email template', 'draft'],
  '/reports': ['report', 'reports', 'mis'],
  '/report-builder': ['build report', 'custom report', 'group by'],
  '/insights': ['anomaly', 'cost anomaly', 'lead score', 'ai'],
  '/analytics': ['charts', 'trends', 'breakdown'],
  '/forecast': ['projection', 'prediction', 'outlook'],
  '/data-quality': ['duplicates', 'duplicate', 'clean data', 'data health'],
  '/tasks': ['todo', 'to do', 'task', 'work'],
  '/approvals': ['approve', 'pending approval', 'sign off'],
  '/calendar': ['schedule', 'meeting', 'events', 'appointments'],
  '/team': ['org chart', 'hierarchy', 'reporting', 'who reports'],
  '/field': ['attendance', 'site', 'labour', 'workers on site'],
  '/site-photos': ['photo', 'photos', 'site picture', 'progress photo'],
  '/voice-note': ['voice', 'dictate', 'speak', 'record note'],
  '/glossary': ['meaning', 'definition', 'what does', 'jargon', 'term'],
  '/settings': ['profile', 'preferences', 'password', 'account'],
  '/admin': ['users', 'roles', 'add user', 'permissions', 'settings'],
  '/audit': ['who did', 'history', 'log', 'audit'],
};
